---

- name: 'Change time zone'
  timezone:
    name: "{{time_zone}}"
    
#- name: 'Template out Netplan YAML to configure networking'
#  template: 
#    src: ./templates/99_config.yaml.tpl
#    dest: /etc/netplan/99_config.yaml
    
#- name: 'Applying Netplan Configuration'
#  command: netplan apply
#  become: yes
#  become_method: sudo

#- name: Remove unneed packages
#  include: remove-pkgs.yaml

- name: Remove unneed packages
  apt:
    name:
      - friendly-recovery 
      - apport
      - landscape-common
      - popularity-contest
    purge: yes
    state: absent

#- name: Remove snapd
#  include: remove-snap.yaml
- name: Remove default snaps
  community.general.snap:
    name: 
    name:
      - lxd
      - core18
      - snapd
    state: absent
    when: '"snapd" in ansible_facts.packages'

- name: Remove snapd package
  apt:
    name: snapd
    purge: yes
    state: absent

- name: Delete snap directory
  file:
    state: absent
    path: /snap

- name: Delete var snap directory
  file:
    state: absent
    path: /var/snap

- name: Delete var lib snapd directory
  file:
    state: absent
    path: /var/lib/snapd

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist
    update_cache: yes
  become: yes
 
- name: Update all packages to latest versions
  apt:
    name: "*"
    state: latest
    update_cache: yes
  become: yes
